// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AeFtP-PDVw9Zz3VMbmjtcy3NWy7PfO8',
    appId: '1:944771787246:web:74d5a6a36d7680d203c6ff',
    messagingSenderId: '944771787246',
    projectId: 'newsapp-d4985',
    authDomain: 'newsapp-d4985.firebaseapp.com',
    storageBucket: 'newsapp-d4985.firebasestorage.app',
    measurementId: 'G-M1S8NH8HFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe131fEzcLaEOkOhGlsTBU7DRT7sbD3X8',
    appId: '1:944771787246:android:a86bcef164311ace03c6ff',
    messagingSenderId: '944771787246',
    projectId: 'newsapp-d4985',
    storageBucket: 'newsapp-d4985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABHVUbG7chjcoEACglmGcqWdLWpPa4Am0',
    appId: '1:944771787246:ios:efecb96507af685f03c6ff',
    messagingSenderId: '944771787246',
    projectId: 'newsapp-d4985',
    storageBucket: 'newsapp-d4985.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABHVUbG7chjcoEACglmGcqWdLWpPa4Am0',
    appId: '1:944771787246:ios:efecb96507af685f03c6ff',
    messagingSenderId: '944771787246',
    projectId: 'newsapp-d4985',
    storageBucket: 'newsapp-d4985.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4AeFtP-PDVw9Zz3VMbmjtcy3NWy7PfO8',
    appId: '1:944771787246:web:f65ea8866d121b6003c6ff',
    messagingSenderId: '944771787246',
    projectId: 'newsapp-d4985',
    authDomain: 'newsapp-d4985.firebaseapp.com',
    storageBucket: 'newsapp-d4985.firebasestorage.app',
    measurementId: 'G-H3MXFYQ98Y',
  );
}
